### ISSUE TITLE
RPKI queries with HTTP Archive/ Google CrUX data (CDNs)

### ISSUE THREAD

**Issue by L3thal14** [InternetHealthReport/iyp-notebooks#1]
Let us consider this query for example:
```
MATCH (:Ranking {name:'Tranco top 1M'})-[r:RANK]-(d:DomainName)-[:PART_OF]-(h:HostName)-[:RESOLVES_TO]-(i:IP)-[:PART_OF]-(pfx:Prefix)-[:ORIGINATE]-(:AS)-[:CATEGORIZED {reference_org:'BGP.Tools'}]-(t:Tag {label:'Content Delivery Network'})
WITH DISTINCT pfx
MATCH (pfx)-[:CATEGORIZED]-(t:Tag)
WHERE t.label = 'RPKI Valid' OR t.label STARTS WITH  'RPKI Invalid'
RETURN COUNT(DISTINCT pfx.prefix) AS nb_valid
```
On taking a closer look at `(d:DomainName)-[:PART_OF]-(h:HostName)-[:RESOLVES_TO]-(i:IP)`, these seem to be using the `OpenINTEL` as the `reference_org`([info](https://github.com/InternetHealthReport/internet-yellow-pages/tree/main/iyp/crawlers/openintel)). 

My Workflow:
- Extract HTTP request URLs from the HTTP Archive data (uses the Google CrUX list for crawls). 
- Extract hostname for each request. Resolve it to an IP and match it with an IP-prefix and continue with the rest of the query mentioned above.
- The issue is that most of the hostnames are not present in the dataset and hence, are not resolved to an IP because of this reason:
`While OpenINTEL runs measurements to a variety of domain names, IYP currently only fetches data for the [Tranco top 1 million list](https://data.openintel.nl/data/tranco1m/) and the CISCO Umbrella top 1 million list since it combines rankings.` 

I wanted to know whether there is any other `reference_org` I could gather this data from.

PS. I do see that HTTP Archive dataset crawler is in the project pipeline and Google CrUX dataset inclusion is already in process.

**Comment by romain-fontugne** [comment]
Hi,

Thanks, that's an excellent question. Yes, we are currently working on integrating CrUX in IYP and I'm also discussing with OpenINTEL folks to get CrUX IPs from them. So this should be doable very soon. 

In the meantime, you can also try to remove the www. part of urls you get in Crux. Currently a lot of the domain names we get from OpenINTEL don't include www. That's a dirty trick, but I wonder how many hostnames are recovered like that.

**Comment by L3thal14** [comment]
Thanks for the swift response. I am actually using the HTTP archive data which crawls the landing page of the CrUX urls.
For example, here is a sample from the dataset:
| page_id | pageid | page_rank | page_url | request_url | request_type | request_mimetype |
| --- | --- | --- | --- | --- | --- | --- |
| 13091627 | 13091627 | 5000 | https://www.lotterypost.com/ | https://token.rubiconproject.com/khaos.json?gdpr=0 |  script | application/json |


In this case, `page_url` is the CrUX URL, `request_url` is the URL of the resource being requested while crawling the landing page. So, I would extract `token.rubiconproject.com` from this, resolve it to an IP and execute the rest of the query, which I believe would not be possible with OpenINTEL if I am not wrong.

PS. If there are plans to include HTTP Archive dataset, it already includes the page ranks for the entire global CrUX list (not just the top one-million), so you could just avoid running the global CrUX crawler altogether and just gather country-wise lists.

**Comment by romain-fontugne** [comment]
Ah ok, I see. Yes, I don't think OpenINTEL is planning to go through all URLs in HTTP archive. Let's start with Crux and then see how we can add HTTP archive  (which is on our list but no clear plans yet to integrate it).

> PS. If there are plans to include HTTP Archive dataset, it already includes the page ranks for the entire global CrUX list (not just the top one-million), so you could just avoid running the global CrUX crawler altogether and just gather country-wise lists.

Thanks that's good to know. Yes, personally I'm very interested in the country-wise lists, we lack regional rankings.
